# This workflow will build a run Jacoco tests with Maven and send the coverage report to coveralls
# For more information see: https://github.com/trautonen/coveralls-maven-plugin

name: Generate Coverage Report and Send it to coveralls

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build coveralls coverage report and send it coveralls via api
        run: mvn coveralls:report -DrepoToken=exO1yW46Iut6puVGNEOSdmsbcMnLnvDrP
